### ISSUE TITLE
Update the zooming feature on mobile and desktop

### ISSUE THREAD

**Issue by candroid-man** [ente-io/frame#244]
On mobile, you cannot zoom in normally, you kind of have to double tap the image and then be able to have full control over the zoom. There is an almost accident protection on it unless you do that, and it is super annoying. 

For desktop, when you click it zooms in like 10x and there is no way of controlling it, so maybe a slider would be a good idea.

**Comment by ua741** [comment]
Hey @candroid-man,
Thank you for reporting this issue. 

On mobile, we have identified one issue due to the zoom feature doesn't work intermittently.  For each image, we first show a small thumbnail, then replace it with a large thumbnail, and in the end, we load the actual image. During these transitions, the zoom function doesn't work as expected. 

We will update here once the fix for this issue is released on appstores.
