### ISSUE TITLE
Make the Play Store and F-Droid versions the same package

### ISSUE THREAD

**Issue by candroid-man** [ente-io/frame#409]
Currently Android sees the Play Store app and F-Droid app as completely different apps. Usually for apps on F-Droid if you have the app already installed from the Play Store, F-Droid will show it as installed and allows you to update it from F-Droid.

**Comment by vishnukvmd** [comment]
Hey, the dependencies and release cycles for F-Droid are different from that of PlayStore, and we intentionally kept them as separate packages to allow our internal testers to keep all variants installed at the same time.

In addition, retaining separate package names also allows us to selectively force-update the relevant variant, when necessary.

This should ideally only be a one-time inconvenience for users switching from one store to another.  If it turns out to be otherwise, we will reconsider this :)
